spring:
  datasource:
    url: jdbc:mysql://192.168.0.116:3306/talci_prod
    username: talci_prod_user
    password: talci
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: false